import LegalPage, { type LegalSection } from "@/components/legal/LegalPage";

const sections: LegalSection[] = [
  { title: "Introduction", paragraphs: ["HONG KONG MACHINING GROUP CO., LIMITED (\"we\", \"us\", or the \"Company\") operates the Origin Wallet platform. This Privacy Policy explains how the Company handles information in connection with its operation of Origin Wallet when you visit the website, create or use an account, contact us, or use services that reference this Policy. Third-party providers may separately process information under their own responsibilities and privacy terms."] },
  { title: "Information We Collect", paragraphs: ["The information we collect depends on how you interact with us and which services you use."], items: ["Identity and contact information, such as name, date of birth, email address, telephone number, residential or business address, and identification information.", "Account and business information, such as login details, role, organisation details, ownership or representative information, and preferences.", "Transaction and financial information needed to provide requested services, such as payment instructions, recipient details, currency, amount, account references, transaction history, and supporting information.", "Technical and usage information, such as IP address, device and browser information, pages viewed, timestamps, diagnostic data, and interactions with the website.", "Communications and support information, including messages, enquiries, feedback, and records of assistance provided."] },
  { title: "How We Use Information", paragraphs: ["We use information to provide and operate the website and services, create and administer accounts, process and track instructions, communicate with you, personalise the user experience, maintain records, improve functionality, and respond to support or business enquiries."] },
  { title: "Legal and Operational Purposes", paragraphs: ["We may process information where reasonably necessary to administer the platform, support identity or eligibility checks performed through relevant workflows, prevent and investigate fraud or misuse, secure accounts and systems, manage operational and financial risk, comply with valid legal requests and applicable obligations, enforce agreements, establish or defend legal claims, and protect users, the Company, and others.", "The basis and requirements for processing may differ by location, service, and the role of each party. This Policy does not claim compliance with a particular privacy regime where that has not been separately established."] },
  { title: "Information Sharing", paragraphs: ["We may share information when needed to provide a requested service, follow your instructions, operate and protect the platform, complete a corporate transaction, comply with law, or protect legal rights. Depending on the service, recipients may include Nium, other payment participants, banks, counterparties, professional advisers, authorities, and other parties involved in a transaction."] },
  { title: "Service Providers and Third Parties", paragraphs: ["Origin Wallet uses services supported by Nium, a third-party financial and payment platform/provider, under the Company's commercial relationship with Nium. We may also use service providers for hosting, communications, customer support, identity-verification support, security, translation, and payment operations. Depending on their role, these parties may process information on our behalf or under their own legal responsibilities. Third-party websites and services are governed by their own privacy notices."] },
  { title: "Data Security", paragraphs: ["Information-security responsibilities may be shared between the Company and relevant service providers according to their respective roles. No method of transmission or storage is completely secure, so we cannot guarantee absolute security. You should use strong credentials and notify us promptly of suspected unauthorised account activity."] },
  { title: "Data Retention", paragraphs: ["Retention and deletion depend on the Company's role, provider requirements, and applicable obligations. Retention periods may vary according to the information, service, risk, and relevant requirements."] },
  { title: "International Data Transfers", paragraphs: ["The Company and the providers or transaction participants supporting a service may process information in countries other than the country where it was collected. Privacy and data-protection rules may differ across those locations. Where a transfer is subject to specific legal requirements, the responsible party will determine and apply the measures required for its role."] },
  { title: "Cookies and Similar Technologies", paragraphs: ["Origin Wallet uses browser storage and cookies for functional purposes. This includes local storage for the cookie-consent record, website and translation-language preferences, and exchange-rate caching; session storage for authentication-session information; and the Google Translate `googtrans` cookie when translation is selected. Some account interface components may also store a UI preference cookie. You can manage or clear these technologies through your browser, although doing so may affect functionality."] },
  { title: "Your Rights", paragraphs: ["Depending on your location and the circumstances, you may have rights to request access to, correction of, deletion of, restriction of, or a copy of certain personal information, or to object to particular uses. These rights may be subject to legal exceptions and identity verification. Contact us to make a request; we will assess it under the rules applicable to the relevant request."] },
  { title: "Children's Privacy", paragraphs: ["Origin Wallet services are not directed to children, and we do not knowingly seek personal information from children who are not legally able to use the relevant service. If you believe a child has provided information without appropriate authorisation, please contact us so we can review it."] },
  { title: "Changes to This Policy", paragraphs: ["We may update this Policy to reflect changes to our services, practices, technology, or relevant requirements. We will publish the revised Policy here and update the date at the top. Additional notice will be provided when reasonably practicable or required for a material change."] },
  { title: "Contact Information", paragraphs: ["For privacy questions or requests concerning the Company's operation of Origin Wallet, contact support@originwallet.asia or use the contact page. To help us respond, describe your request and the Origin Wallet service or interaction it relates to. We may need to verify your identity before acting on certain requests."] },
];

const Privacy = () => (
  <LegalPage
    title="Privacy Policy"
    description="Learn how Origin Wallet collects, uses, shares, retains, and protects information when you use its website and services."
    path="/privacy"
    introduction="This Policy describes our information practices and the choices that may be available to you."
    sections={sections}
  />
);

export default Privacy;
